### ISSUE TITLE
Select method on client

### ISSUE THREAD

**Issue by Gabriel-Fachini** [RobertCraigie/prisma-client-py#680] opened 2023-01-23 20:25 UTC
## Problem
Overfetching data from database.

## Suggested solution
Develop a select method, who already exists on original prisma for javascript.

**Comment by RobertCraigie** [comment] 2023-01-23 22:59
This is a duplicate of #19. There is also a WIP implementation of the second solution mentioned in that issue that will be finished soon.

**Closed by RobertCraigie** 2023-01-23 22:59 UTC
