### ISSUE TITLE
Singleton Class

### ISSUE THREAD

**Issue by danielweil** [RobertCraigie/prisma-client-py#74] opened 2021-09-28 16:30 UTC
Hey, in the original Prisma Library, I used a singleton class to instantiate the client only once and then use it in my code. I did not need to connect and disconnect it everytime as well.

I tried doing something similar here but I am having a rough time to import the singleton class from another module.

Do you think it can be done?

Thanks!

**Comment by RobertCraigie** [comment] 2021-09-28 16:44
Yes, this should be possible.

However you will have to manage the client state yourself, unlike the Node Prisma Client we do not implicitly connect to the database for you. This is by design to prevent a footgun with connecting and disconnecting from the database frequently by accident.

There two solutions for this that I am aware of:

- If the framework you are using provides an event like `on_startup` then you should connect inside that callback.
- Check if the client is connected on each request and connect if it is not.

Example for the second solution:

```py
async def handler() -> None:
    if not client.is_connected():
        await client.connect()
    ...
```

**Comment by RobertCraigie** [comment] 2021-09-28 16:46
What issues were you encountering?

**Comment by danielweil** [comment] 2021-09-28 17:10
My client file is located a couple of folder previous to where my functions are. So I am having issues importing it,

Why is the second aprouch bad? Do you recommend the third one? Is there any need to disconnect?

**Comment by danielweil** [comment] 2021-09-28 17:20
Can you share an idea for the singleton?

**Comment by RobertCraigie** [comment] 2021-09-28 17:27
It's generally considered a bad practice to do any expensive operations on import.

You should be able to do relative imports, e.g. `from ...db import client` all you need to enable this is to have an `__init__.py` file in every directory.

Yeah sure, I'll send an example as soon as possible.

**Comment by danielweil** [comment] 2021-09-28 18:33
Thanks!

**Comment by danielweil** [comment] 2021-09-28 22:24
Last thing, do I need to disconnect after I use the client?

**Comment by RobertCraigie** [comment] 2021-09-29 08:05
> do I need to disconnect after I use the client?

Disconnecting is done for you when the python process is terminated or the client instance is deleted.

However I would still recommend explicitly disconnecting when you can but as you're using serverless functions then you shouldn't explicitly disconnect as you shouldn't have to reconnect on every hot function invocation.

**Comment by RobertCraigie** [comment] 2021-09-29 11:20
@danielweil here's an example showing how to share the same Prisma Client Python instance between multiple modules:

https://github.com/RobertCraigie/prisma-reproductions/tree/main/py-singleton

**Comment by RobertCraigie** [comment] 2021-10-02 10:25
@danielweil going to go ahead and close this, please re-open if you have any more questions, thanks!

**Closed by RobertCraigie** 2021-10-02 10:25 UTC
Labels: kind/question
